image: alpine/edge
packages:
  - ruby
tasks:
  - install: |
      sudo gem install bundler --no-rdoc --no-ri
  - deploy: |
      pwd
      ls
      export REDIS_URL=$(cat ~/.redis-url | tr -d '\n')
      bundle
      bundle exec puma -C puma.rb

secrets:
  - 966f7e3f-5531-4dff-a179-b22879666fce
