image: alpine/edge
sources:
  - https://git.sr.ht/~broothie/werds
packages:
  - ruby
tasks:
  - install: |
      sudo gem install bundler -v 1.16.6 --no-rdoc --no-ri
      sudo gem install puma -v 3.12.0 --no-rdoc --no-ri -- --with-cppflags=-I/usr/local/opt/openssl/include
  - deploy: |
      export REDIS_URL=$(cat ~/.redis-url | tr -d '\n')
      cd werds
      bundle install
      bundle exec puma -C puma.rb

secrets:
  - 966f7e3f-5531-4dff-a179-b22879666fce
