image: alpine/edge
sources:
  - https://git.sr.ht/~broothie/werds
packages:
  - ruby
  - ruby-dev
  - ruby-bundler
  - make
  - gcc
  - libc-dev
tasks:
  - deploy: |
      export REDIS_URL=$(cat ~/.redis-url | tr -d '\n')
      cd werds
      bundle install
      bundle exec puma -C puma.rb

secrets:
  - 966f7e3f-5531-4dff-a179-b22879666fce
